# pull official base image
FROM tiangolo/uwsgi-nginx-flask:python3.8

# set work directory
WORKDIR /usr/src/app


# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./backend/requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

ENV LISTEN_PORT 5000
EXPOSE 5000

# copy project
COPY ./backend/ /usr/src/app/