version: "3.9"
services:
  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile.frontend.prod
    links:
      - "backend:backend"
      - "database:database"
    ports:
      - "80:80"
    environment:
      - API_HOST=backend
      - API_PORT=5000
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend.prod
    environment:
      - DB_URL=mongodb://database:27017/part
    ports:
      - "5000:5000"
  database:
    image: "mongo:latest"
    ports:
      - "27018:27017"
