version: "3.9"
services:
  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile.frontend.prod
    links:
      - "backend:backend"
      - "database:database"
    ports:
      - "8080:80"
    environment:
      - API_HOST=backend
      - API_PORT=5000
  backend:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend.prod
    environment:
      - DB_URL=mongodb://database:27017/part
  database:
    image: "mongo:latest"
    volumes:
      - dbvolume:/etc/mongo
  
volumes:
  dbvolume:
    external: false
